server.port=8080
spring.web.error.include-message=always
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
spring.jackson.serialization.INDENT_OUTPUT=true

# Spring Setup
logging.level.root=WARN
logging.level.org.springframework=WARN

# H2 Database Setup
spring.datasource.url=jdbc:h2:file:/resources/db/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
logging.level.org.springframework.security=DEBUG